print("Welcome to Kayak 3.0. Let's plan an adventure!")
enter = int(input("Enter 1 to continue or 2 to Quit: "))
while enter == 1:
    destination = input("Do you have a destination in mind? ").lower()
    if destination == "yes":
        print("Great! Let's start planning your trip.")
        location = input("Where would you like to go? ").lower()
        print("Awesome! " + location + " sounds like a great trip.")
        transport = input("How would you like to get there? : Plane/train or car : ").lower()
        if transport == "plane" or transport == "train":
            print("Great! Let's book your ticket.")
            class_type = input("Would you like to fly (First class / Business / Economy) ? ").lower()
            luggage = int(input("Enter baggae weight in kg? "))
            if luggage >= 21 and class_type == "First" or class_type == "Business":
                print("You can have extra  luggage.")
            elif luggage < 21 and class_type == "First" or class_type == "Business":
                print("You can bring more if you want") 
            else:
                print("Warning , You have exceeded the limit.") 
        elif transport == "car":
            print("Great! Let's book your car.")
            car_type = input("What type of car would you like? : Sedan / SUV : ").lower()
            if car_type == "sedan":
                print("Great! Sedan is booked for you.")
            elif car_type == "suv":
                print("Great! SUV is booked for you.")
            else:
                print("Sorry, we don't have that type of car.")
        elif transport =="train":
            print("Great! Let's book your train ticket.")
            train_class = input("What class would you like to travel in? : First / Second : ").lower()
            if train_class == "first":
                print("Great! First class is booked for you.")
            elif train_class == "second":
                print("Great! Second class is booked for you.")
            else:
                print("Sorry, we don't have that class.")
        else:
            print("Sorry, we don't provide that transport service.")   
     
    else:
        print("No problem! Let's explore some destinations together.")
        print("Here are some popular destinations:")
        print("1. Tokyo, Japan")
        print("2. Paris, France")
        print("3. New York City, USA")
        print("4. Sydney, Australia")
        print("5. Cape Town, South Africa")
        print("6. Rio de Janeiro, Brazil")
        print("7. Dubai, UAE")
        print("8. Rome, Italy")
        print("9. London, UK")
        print("10. Bangkok, Thailand")
        print("11. Barcelona, Spain")
        print("12. Los Angeles, USA")
        print("13. Toronto, Canada")
        print("14. Singapore")
        print("15. Istanbul, Turkey")
        print("16. Seoul, South Korea")
        print("17. Amsterdam, Netherlands")
        print("18. Berlin, Germany")
        print("19. Prague, Czech Republic")
        print("20. Buenos Aires, Argentina")
        print("21. Mumbai, India")
        print("22. Moscow, Russia")
        print("23. Cairo, Egypt")
        print("24. Mexico City, Mexico")
        print("25. Athens, Greece")
        print("26. Havana, Cuba")
        print("27. Reykjavik, Iceland")
        print("28. Marrakech, Morocco")
        print("29. Cape Town, South Africa")
        print("30. Kyoto, Japan")
        print("31. Vancouver, Canada")
        print("32. Dubai, UAE")
        print("33. Budapest, Hungary")
        print("34. Vienna, Austria")
        print("35. Buenos Aires, Argentina")
        print("36. Sydney, Australia")
        print("37. Prague, Czech Republic")
        print("38. Barcelona, Spain")
        print("39. Hong Kong, China")
        print("40. Amsterdam, Netherlands")
        print("41. Istanbul, Turkey")
        print("42. Singapore")
        print("43. Milan, Italy")
        print("44. Bangkok, Thailand")
        print("45. Lisbon, Portugal")
        print("46. Seoul, South Korea")
        print("47. Rome, Italy")
        print("48. Tokyo, Japan")
        print("49. Paris, France")
        print("50. New York City, USA")
        location = input("Where would you like to go? ").lower()             